### ISSUE TITLE
Mod1 - Something happened on the drag and drop on practice page

### ISSUE THREAD

**Issue by viviancan** [dryuen/ist5313-final-project-template#116]
![screen shot 2017-11-29 at 6 16 41 pm](https://user-images.githubusercontent.com/29210380/33406262-9c037794-d531-11e7-9c6b-08c1135b2503.png)

**Comment by ldalum** [comment]
Tested on all browsers, on various computers (mac and pc). It is functioning, perhaps it was just a glitch?
